### ISSUE TITLE
Can't Look for Tests in Multiple Directories

### ISSUE THREAD

**Issue by sergio97** [thusoy/grunt-nose#11]
I'm trying to tell nose to look in 2 different directories for tests. Here's the grunt-nose section of my Gruntfile:

```js
    nose: {
      options: {
        verbose: true,
        randomize: true,
        virtualenv: "venv",
      },
      run_tests: {
        src: ["tests/master/", "tests/slave/"],
      },
```

but it looks like grunt-nose is only looking for tests in the second directory in src. In this example, only slave tests. If I make src: ["tests/master/"], it will run master tests.
I also tried using options: {where: ...} but it gives a warning saying to use src instead.

Ubuntu 14.04 64-bit
python 2.7.6
grunt 0.4.4
grunt-nose 0.4.0

Thank you for making grunt-nose! I really find it useful and use it almost every day!

**Comment by thusoy** [comment]
Thanks for reporting this, I'll have a look at it tomorrow! Can you work around it in the meantime by splitting the different folders to different task targets?

**Comment by thusoy** [comment]
@sergio97 This should be solved in the newly pushed v1.0.0, give it a spin and let me know if it doesn't work. :)

**Comment by sergio97** [comment]
Your patch resolved the issue. Thank you!

**Comment by sergio97** [comment]
Reading your commit, I am a little bit worried about test_that_loading_several_test_directories_work() lol.

**Comment by thusoy** [comment]
Haha, make sure you notice that the test works if that test is executed (which is tested by node), the actual test is not written in python ;)
